apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  #namespace: <your namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: mjcheveste/app-loggenerator:latest
        env:
        - name: LOG_MESSAGE
          value: "Mensaje personalizado"
        - name: LOG_LENGTH
          value: "30"
        - name: LOG_PERIOD
          value: "5"